// Rebuild careers-data.js:
//  - replace template tagline/desc/overview with real BLS text
//  - replace guessed growth/salary with BLS median pay + projected growth
//  - rewrite the AI-resilience lines in plain language
//  - tag every career (flagship too) with degree background + interest tags
// Writes scratch/careers-data.new.js first for review.
const fs = require('fs');
const bls = require('./bls-pages.json');

global.window = {};
require('../careers-data.js');
const flagship = global.window.CAREERS_FLAGSHIP;
const globalList = global.window.CAREERS_GLOBAL;

// ---------------------------------------------------------------- AI copy ----
// Plain-language replacements for the eleven templated resilience lines. Each
// used to name jobs from an unrelated field (an accountant's card talked about
// investment bankers), so they are rewritten at field level.
const AI_LINES = {
  'AI-Augmented Synthesis': {
    tag: 'automation',
    label: 'Routine Drafting Is Automated',
    text: 'Spreadsheets, standard reports and first drafts are already generated by software. What clients still pay for is judgement: reading a situation, deciding what matters, and standing behind the answer.'
  },
  'AI-Enhanced Creation': {
    tag: 'automation',
    label: 'Options Are Cheap Now',
    text: 'Generative tools produce a hundred variations in minutes, so the value has moved to taste: knowing which one is right and why. Direction, briefs and client trust are the parts that hold up.'
  },
  'AI-Augmented Frontier': {
    tag: 'automation',
    label: 'Tools Write More Of The Code',
    text: 'Copilots and agents draft, test and refactor code, which raises what a developer is expected to ship. Designing the system, reviewing what the machine produced, and owning failures still sit with a person.'
  },
  'Human-Empathy Protected': {
    tag: 'people',
    label: 'Lesson Plans Are Easy To Generate',
    text: 'Outlines, worksheets and quizzes take seconds to produce. Motivation, reading a room and holding a class together are not things software does.'
  },
  'AI-Augmented Design': {
    tag: 'automation',
    label: 'Software Explores The Options',
    text: 'Generative design and simulation run thousands of variants quickly. Choosing one, checking it against physics, safety rules and cost, and signing it off stays human.'
  },
  'AI-Powered Discovery': {
    tag: 'automation',
    label: 'Models Read The Data First',
    text: 'Machine learning sifts through survey data, images and signals faster than any team. Framing the question, checking the result and deciding what it means is where people stay involved.'
  },
  'AI-Powered Optimization': {
    tag: 'automation',
    label: 'Forecasting Keeps Improving',
    text: 'Climate and energy models now simulate scenarios that once took teams months. Field work, local knowledge and policy negotiation are much slower to automate.'
  },
  'Physical-Dexterity Protected': {
    tag: 'protected',
    label: 'The Work Is Physical',
    text: 'Every job is a different room, a different fault, a different set of tools. Work in unstandardised physical spaces is the hardest thing for software to take over.'
  },
  'AI-Augmented Legal Search': {
    tag: 'automation',
    label: 'Search And Summary Are Automated',
    text: 'AI reads contracts and case history in seconds. Argument, strategy, ethics and the responsibility of advising a client stay with the lawyer.'
  }
};

// Three of the eleven old lines share the "Human-Empathy Protected" prefix but
// point at different fields (teaching, care work, clinical medicine), so they
// are matched on their body text instead.
function aiLineFor(career) {
  const raw = career.aiImpact || '';
  const prefix = raw.split('\u2014')[0].trim();
  if (prefix === 'Human-Empathy Protected') {
    if (/classroom|teaching|lesson/i.test(raw)) {
      return AI_LINES['Human-Empathy Protected'];
    }
    if (/diagnostic|bedside|clinical|imaging/i.test(raw)) {
      return {
        tag: 'people',
        label: 'Diagnostics Are Assisted',
        text: 'Imaging, lab results and records are increasingly read by software first. Examination, procedures, consent and the conversation with the patient are not.'
      };
    }
    return {
      tag: 'people',
      label: 'Presence Is The Job',
      text: 'Comfort, trust and physical care are the reason the role exists. Tools can monitor and remind, but they cannot sit with someone or speak for the family.'
    };
  }
  return AI_LINES[prefix] || { tag: 'automation', label: prefix, text: raw.split('\u2014').slice(1).join('\u2014').trim() || raw };
}

// ------------------------------------------------------------ text helpers ---
function sentences(s) {
  return (s.match(/[^.!?]+[.!?]+/g) || [s]).map(x => x.trim()).filter(Boolean);
}

function decap(s) {
  return s.charAt(0).toLowerCase() + s.slice(1);
}

function capFirst(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

// "Accountants and auditors prepare and examine financial records."
//   -> "Prepare and examine financial records."
function taglineFrom(summary, title) {
  if (!summary) return '';
  const first = sentences(summary)[0] || summary;
  const t = title.toLowerCase();
  const s = first.toLowerCase();
  if (s.startsWith(t)) {
    const rest = first.slice(title.length).replace(/^[\s,:-]+/, '');
    if (rest.length > 8) return capFirst(rest);
  }
  // Subject is shorter than the page title ("Announcers present ..."): drop
  // just the leading word when it matches the title's first word.
  const firstWord = title.split(/\s+/)[0].toLowerCase();
  const words = first.split(' ');
  if (firstWord && words.length > 6 && s.startsWith(firstWord + ' ')) {
    const rest = words.slice(1).join(' ');
    if (rest.length > 12) return capFirst(rest);
  }
  return first;
}

// Card copy: everything after the first sentence of the overview, so the card
// does not repeat the tagline. Single-sentence overviews fall back to the BLS
// duty bullets, which read as work rather than a definition.
function descFrom(bls) {
  const overview = bls.overview || '';
  const parts = sentences(overview);
  let out = '';
  if (parts.length >= 2) {
    out = parts.slice(1).join(' ').trim();
    if (out.length < 60) out = parts.slice(0, 2).join(' ');
  } else if (bls.duties && bls.duties.length) {
    out = bls.duties.slice(0, 3).map(d => {
      const clean = d.replace(/[.;]+$/, '');
      return capFirst(clean);
    }).join('; ') + '.';
  } else {
    out = parts[0] || bls.summary || '';
  }
  if (out.length > 320) {
    const kept = sentences(out);
    let acc = '';
    for (const s of kept) {
      if ((acc + ' ' + s).trim().length > 320) break;
      acc = (acc + ' ' + s).trim();
    }
    out = acc || kept[0];
  }
  return out;
}

// ------------------------------------------------------- BLS field mapping ---
function growthLabel(pct, phrase, dir) {
  const p = (phrase || '').toLowerCase();
  if (dir === 'decline') return 'Decline';
  if (p.includes('much faster')) return 'Much faster than average';
  if (p.includes('faster than')) return 'Faster than average';
  if (p.includes('slower')) return 'Slower than average';
  if (p.includes('little or no change') || pct === 0) return 'Little or no change';
  if (p.includes('as fast')) return 'As fast as average';
  return 'As fast as average';
}

function demandFor(pct, dir) {
  if (dir === 'decline') return 'Falling';
  if (pct >= 20) return 'Extreme';
  if (pct >= 10) return 'Very High';
  if (pct >= 5) return 'High';
  return 'Steady';
}

// Keep the site's existing rupee convention: scale the whole old string by the
// ratio of the real BLS median to the guess it was built from.
function rescaleSalary(old, medianUsd) {
  if (!old || !medianUsd) return old;
  const usdParts = [...old.matchAll(/\$(\d+)K/g)].map(m => parseInt(m[1], 10));
  if (usdParts.length < 3) return old;
  const oldMid = usdParts[1];
  if (!oldMid) return old;
  const f = (medianUsd / 1000) / oldMid;
  const newUsd = [
    Math.max(1, Math.round((medianUsd * 0.72) / 1000)),
    Math.max(2, Math.round(medianUsd / 1000)),
    Math.max(3, Math.round((medianUsd * 1.9) / 1000))
  ];
  const inr = [...old.matchAll(/(\d+)-(\d+) LPA/g)].map(m => [
    Math.max(1, Math.round(parseInt(m[1], 10) * f)),
    Math.max(2, Math.round(parseInt(m[2], 10) * f))
  ]);
  const leadInr = old.match(/(\d+) LPA\+/);
  const lead = leadInr
    ? Math.max(3, Math.round(parseInt(leadInr[1], 10) * f))
    : Math.max(3, Math.round(newUsd[2] * 0.42));
  if (inr.length < 2) return old;
  return 'Entry: $' + newUsd[0] + 'K / \u20b9' + inr[0][0] + '-' + inr[0][1] + ' LPA \u00b7 ' +
    'Mid: $' + newUsd[1] + 'K / \u20b9' + inr[1][0] + '-' + inr[1][1] + ' LPA \u00b7 ' +
    'Lead: $' + newUsd[2] + 'K+ / \u20b9' + lead + ' LPA+';
}

// ----------------------------------------------------- degree / interest tags -
const DEGREE_RULES = [
  { slug: 'engineering', re: /\b(?:b\.?tech|b\.?e\.?|bachelor of engineering|beng)\b|civil|mechanical|electrical|aerospace|chemical engineering|industrial engineering|automotive|structural|robotic|mechatronic|semiconductor|vlsi|nuclear engineering|petroleum|environmental engineering|instrumentation/ },
  { slug: 'computing', re: /\b(?:bca|b\.?tech in (?:computer|information)|b\.?s\.? (?:in )?(?:computer|software|information))\b|computer science|information technology|software engineering|data science|cybersecurity|game design|artificial intelligence|machine learning|blockchain|full-stack|cloud|devops|data engineering|human-computer/ },
  { slug: 'health', re: /\b(?:mbbs|bds|md|b\.?pharm|bpt|bvsc|bnurs|bsc nursing)\b|dentistr|nursing|pharmac|physiotherap|veterinar|perfusion|public health|biomedical engineering|clinical|medicine|surgery|optometr|audiolog|paramedic|ambulance|nutrition|occupational therapy|speech pathology/ },
  { slug: 'science', re: /\b(?:bsc|b\.?s\.?c|bstat|bmath)\b|\bphysics\b|\bchemistry\b|\bbiolog\w*|\bmathematics\b|\bstatistics\b|\bastronomy\b|\bgeolog\w*|\bzoolog\w*|\bbotany\b|\bmicrobiolog\w*|\bbiotechnolog\w*|\bagricultur\w*|\bmarine (?:biology|science)|environmental science|\bforensic\b|\bpsycholog\w*|\bmeteorolog\w*|\boceanograph\w*|\bquantum\b|\bneuroscience\b/ },
  { slug: 'commerce', re: /\b(?:bcom|b\.?com|bba|b\.?b\.?a)\b|accountanc|finance|commerce|actuarial|entrepreneur|business administration|company secretary|economics/ },
  { slug: 'arts', re: /\b(?:ba|bachelor of arts)\b|history|political science|literature|linguistic|philosophy|sociolog|anthropolog|international relations|public policy|journalism|mass communication|languages|english|liberal arts|psycholog/ },
  { slug: 'law', re: /\b(?:ll\.?b|llb|ba llb|bba llb)\b|\blaw\b|legal|advocat|litigation|judiciary|juris/ },
  { slug: 'education', re: /\b(?:bed|b\.?ed|b\.?el\.?ed|bachelor of education)\b|teaching|pedagogy|instructional design|curriculum/ },
  { slug: 'design', re: /\b(?:bdes|b\.?des|bfa|b\.?f\.?a|barch|b\.?arch)\b|architecture|\bdesign\b|film|animation|visual effects|photography|fashion|interior design|fine art|conservation/ },
  { slug: 'management', re: /\b(?:mba|pgdm)\b|master of business|business management|management strategy/ },
  { slug: 'vocational', re: /\b(?:diploma|iti|polytechnic|certificate|apprenticeship)\b/ },
  { slug: 'any', re: /any bachelor|any degree|open to all backgrounds|regardless of stream/ }
];

const INTEREST_RULES = [
  { slug: 'tech', re: /\b(?:computer|software|programmer|programming|coding|cyber|cloud|database|network|web|website|app|artificial intelligence|machine learning|blockchain|information technology|devops|data scientist|data engineer|algorithm)\w*/ },
  { slug: 'health', re: /\b(?:nurse|nursing|doctor|physician|surgeon|dentist|pharmacist|pharmacy|therapist|therapy|clinic|patient|dental|medical|health|optometrist|audiologist|paramedic|emt|veterinarian|midwife|nutritionist|dietitian|surgeon|hospital|caregiver|physiotherap)\w*/ },
  { slug: 'numbers', re: /\b(?:accountant|accounting|auditor|audit|actuary|actuarial|finance|financial|banker|banking|investment|tax|economist|economics|statistician|statistics|quantitative|payroll|budget|credit|ledger|bookkeep|risk)\w*/ },
  { slug: 'business', re: /\b(?:sales|marketing|manager|management|retail|business|executive|consultant|consulting|negotiat|account executive|product manager|real estate|broker|purchasing|procurement|advertising|public relations|entrepreneur|founder|wholesale|merchandis)\w*/ },
  { slug: 'machines', re: /\b(?:mechanic|machinery|machine|engineer|engineering|technician|tool|equipment|maintenance|repair|weld|electrician|electrical|mechatronic|industrial|manufactur|production|instrument|assembler|fabricat|machinist|installer)\w*/ },
  { slug: 'build', re: /\b(?:construction|carpenter|mason|masonry|plumber|plumbing|roofer|builder|building|architect|architecture|surveyor|concrete|drywall|insulator|ironworker|pipelayer|glazier|flooring|painter|cabinetmaker|heavy equipment)\w*/ },
  { slug: 'outdoors', re: /\b(?:farm|farming|ranch|forestry|forester|conservation|agricultur|environment|park|outdoor|horticultur|landscape|florist|gardener|wildlife|fisher|hunt|geolog|ocean|climate|weather|meteorolog|ranger|timber|logging|grounds|custodial|janitor)\w*/ },
  { slug: 'science', re: /\b(?:scientist|scientif|chemist|chemistry|physicist|physics|biolog|laboratory|lab |research|genetic|microbiolog|astronom|forensic|material science|pharmacolog|toxicolog|biochem|geophysic|zoolog|botanist|ecolog)\w*/ },
  { slug: 'design', re: /\b(?:designer|design|artist|art director|illustrat|animat|photograph|fashion|graphic|interior|draw|paint|sculpt|craft|studio|visual|cartoon|decorat|stylist)\w*/ },
  { slug: 'words', re: /\b(?:writer|writing|author|editor|editing|journalist|reporter|copywrit|translat|interprete|librarian|library|archivist|poet|screenwrit|speech|technical writer|publish|novelist|columnist)\w*/ },
  { slug: 'law', re: /\b(?:lawyer|attorney|judge|legal|paralegal|court|litigat|police|detective|investigator|security|correction|fire inspector|arbitrat|mediat|diplomat|civil service|policy|compliance|immigration|ambassador|prosecut|litigation|law enforcement)\w*/ },
  { slug: 'people', re: /\b(?:counselor|counselling|social work|human resource|community|welfare|childcare|caregiver|home health|receptionist|concierge|customer service|host|funeral|marriage|family|youth|probation|case manager|recruiter|hairdresser|cosmetolog|barber|childcare|companion|personal care)\w*/ },
  { slug: 'teaching', re: /\b(?:teacher|teaching|instructor|trainer|tutor|coach|professor|educator|librarian|principal|school|curriculum|preschool|kindergarten|daycare|teaching assistant|scout)\w*/ },
  { slug: 'transport', re: /\b(?:pilot|driver|aviation|flight|air traffic|captain|truck|delivery|train|rail|maritime|ship|sailor|navigator|chauffeur|taxi|transit|warehouse|freight|logistic|aviator|deckhand|harbor|courier|bridge|tower)\w*/ },
  { slug: 'food', re: /\b(?:chef|cook|baker|food|restaurant|barista|sommelier|culinary|kitchen|butcher|catering|cafeteria|dishwasher|baker)\w*/ },
  { slug: 'sport', re: /\b(?:athlete|sport|fitness|referee|umpire|recreation|athletic|gym|yoga|dancer|dancing|music|musician|singer|perform|actor|entertain|choreograph|exercise)\w*/ }
];

function matchSlugs(rules, text) {
  const out = [];
  for (const r of rules) if (r.re.test(text)) out.push(r.slug);
  return out;
}

function interestTags(career) {
  const text = [
    career.title,
    career.catName,
    (career.roles || []).join(' '),
    (career.desc || '').slice(0, 300)
  ].join(' ').toLowerCase();

  const tags = matchSlugs(INTEREST_RULES, text);

  // Category floor: every career gets at least one home, so no interest filter
  // can end up empty and no career ends up untagged.
  const fallback = {
    tech: 'tech', health: 'health', eng: 'machines', space: 'science',
    eco: 'outdoors', science: 'science', biz: 'business', law: 'law',
    creative: 'design', edu: 'teaching', trades: 'machines', service: 'people'
  }[career.cat];
  if (fallback && !tags.includes(fallback)) tags.unshift(fallback);
  if (!tags.length) tags.push('people');
  return [...new Set(tags)].slice(0, 5);
}

function degreeTags(career, eduSlug) {
  const text = [
    career.title,
    (career.education && career.education.undergradDegrees || []).join(' '),
    (career.education && career.education.postgradDegrees || []).join(' ')
  ].join(' ').toLowerCase();

  const tags = matchSlugs(DEGREE_RULES, text);

  // Vocational routes come from the BLS entry requirement rather than a degree
  // name, so trades that never mention a bachelor still show up.
  if (eduSlug === 'nodegree' || eduSlug === 'diploma') tags.push('vocational');
  if (!tags.length) tags.push('any');
  return [...new Set(tags)].slice(0, 5);
}

function eduLevelFor(career) {
  const b = bls[career.id];
  const raw = b && b.entryEducation ? b.entryEducation : '';
  if (/no formal|high school/i.test(raw)) return 'nodegree';
  if (/postsecondary nondegree|associate|some college/i.test(raw)) return 'diploma';
  if (/master/i.test(raw)) return 'master';
  if (/doctoral|professional/i.test(raw)) return 'doctorate';
  if (/bachelor/i.test(raw)) return 'bachelor';

  const text = ((career.education && career.education.undergradDegrees || []).join(' ') + ' ' +
    (career.education && career.education.postgradDegrees || []).join(' ')).toLowerCase();
  if (/ph\.?d|mbbs|\bmd\b|\bbds\b|ll\.?b|bvsc|doctor of/.test(text)) return 'doctorate';
  if (/m\.?ba|master|m\.?tech|m\.?des|m\.?phil|\bm\.?s\b/.test(text)) return 'master';
  if (/diploma|\biti\b|polytechnic|apprentice/.test(text)) return 'diploma';
  return 'bachelor';
}

// ------------------------------------------------------------------ apply ----
let stats = { bls: 0, taglineOdd: 0, rescaled: 0 };

for (const c of globalList) {
  const b = bls[c.id];
  if (b && b.summary) {
    c.tagline = taglineFrom(b.summary, c.title);
    if (c.tagline && !/[.!?"']$/.test(c.tagline)) c.tagline += '.';
    c.overview = b.overview || b.summary || c.overview;
    c.desc = descFrom(b) || c.desc;
    stats.bls++;
  }
  if (b && b.growthPct !== undefined) {
    c.growth = b.growthPct + '% (' + growthLabel(b.growthPct, b.growthPhrase, b.growthDir) + ')';
    c.demand = demandFor(b.growthPct, b.growthDir);
    c.growthYears = b.growthYears || '';
    c.openings = b.jobs || '';
  }
  if (b && b.medianUsd) {
    const next = rescaleSalary(c.salary, b.medianUsd);
    if (next !== c.salary) stats.rescaled++;
    c.salary = next;
    c.medianPay = b.medianUsd;
  }
  const ai = aiLineFor(c);
  c.aiImpact = ai.label + ' \u2014 ' + ai.text;
  c.aiTag = ai.tag;
  c.edu = eduLevelFor(c);
  c.interests = interestTags(c);
  c.degrees = degreeTags(c, c.edu);
  if (c.tagline && !/[.!?"']$/.test(c.tagline)) stats.taglineOdd++;
}

for (const c of flagship) {
  c.edu = eduLevelFor(c);
  c.interests = interestTags(c);
  c.degrees = degreeTags(c, c.edu);
  const body = (c.aiImpact || '').toLowerCase();
  c.aiTag = /physic|hand|field|site|dexterity|clinical care|bedside/.test(body) ? 'protected'
    : /empathy|human|teaching|counsel|care|people/.test(body) ? 'people' : 'automation';
}

// -------------------------------------------------------------- report -------
const countBy = key => {
  const m = {};
  [...flagship, ...globalList].forEach(c => (c[key] || []).forEach(k => { m[k] = (m[k] || 0) + 1; }));
  return m;
};
console.log('BLS rewrites:', stats.bls, '| salaries rescaled:', stats.rescaled, '| odd taglines:', stats.taglineOdd);
console.log('interests:', countBy('interests'));
console.log('degrees:', countBy('degrees'));
console.log('edu levels:', [...flagship, ...globalList].reduce((m, c) => { m[c.edu] = (m[c.edu] || 0) + 1; return m; }, {}));
console.log('aiTags:', [...flagship, ...globalList].reduce((m, c) => { m[c.aiTag] = (m[c.aiTag] || 0) + 1; return m; }, {}));

console.log('\n--- sample rewrites ---');
for (const id of ['ooh-0-accountants-and-auditors', 'ooh-341-writers-and-authors', 'ooh-342-zoologists-and-wildlife-biologists']) {
  const c = globalList.find(x => x.id === id);
  if (!c) continue;
  console.log('\n# ' + c.title);
  console.log('  tagline: ' + c.tagline);
  console.log('  desc:    ' + c.desc);
  console.log('  growth:  ' + c.growth + ' | demand ' + c.demand);
  console.log('  salary:  ' + c.salary);
  console.log('  ai:      ' + c.aiImpact);
  console.log('  edu:     ' + c.edu + ' | degrees ' + c.degrees + ' | interests ' + c.interests);
  const probe = [c.title, c.catName, (c.roles || []).join(' '), (c.desc || '').slice(0, 300)].join(' ').toLowerCase();
  console.log('  matches: ' + matchSlugs(INTEREST_RULES, probe).join(','));
}

console.log('\n--- sanity ---');
const all = [...flagship, ...globalList];
console.log('empty taglines:', all.filter(c => !c.tagline || c.tagline.length < 8).map(c => c.title));
console.log('short desc:', all.filter(c => !c.desc || c.desc.length < 40).map(c => c.title));
console.log('empty overview:', all.filter(c => !c.overview).map(c => c.title));
console.log('odd taglines:', all.filter(c => c.tagline && !/[.!?"\']$/.test(c.tagline)).map(c => c.title + ' :: ' + c.tagline));
console.log('no interest tags:', all.filter(c => !c.interests || !c.interests.length).length);
console.log('no degree tags:', all.filter(c => !c.degrees || !c.degrees.length).length);

// -------------------------------------------------------------- write out ----
const header =
  '// Global Careers & Occupations Dataset (404 Detailed Pathways \u00b7 50,000+ Indexed Titles)\n' +
  '// Pay, growth and job descriptions for OOH entries come from the U.S. Bureau of\n' +
  '// Labor Statistics Occupational Outlook Handbook (https://www.bls.gov/ooh/).\n' +
  '// Auto-generated by scripts/build_world_careers.js\n';

const body =
  '(function() {\n' +
  '  const root = typeof window !== \'undefined\' ? window : (typeof global !== \'undefined\' ? global : this);\n' +
  '  root.CAREERS_FLAGSHIP = ' + JSON.stringify(flagship) + ';\n' +
  '  root.CAREERS_GLOBAL = ' + JSON.stringify(globalList) + ';\n' +
  '  root.CAREERS_ALL = root.CAREERS_FLAGSHIP.concat(root.CAREERS_GLOBAL);\n' +
  '  if (typeof module !== \'undefined\' && module.exports) {\n' +
  '    module.exports = { CAREERS_FLAGSHIP: root.CAREERS_FLAGSHIP, CAREERS_GLOBAL: root.CAREERS_GLOBAL, CAREERS_ALL: root.CAREERS_ALL };\n' +
  '  }\n' +
  '})();\n';

fs.writeFileSync(__dirname + '/careers-data.new.js', header + body);
console.log('\nwrote scratch/careers-data.new.js', (header + body).length, 'bytes');
